$primary = rgb(7b67e4)
$surface = rgb(1b1924)
$secondary = rgb(ac5cd6)
$error = rgb(fd4663)
$tertiary = rgb(cc66bc)
$surface_lowest = rgb(0d0c12)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
