
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim before DPMS
#listener {
#    timeout = 150                               # 2.5min
#    on-timeout = brightnessctl -s set 10
#    on-resume = brightnessctl -r
#}

# Screen off
listener {
    timeout = 330                               # 5.5min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock later (optional)
listener {
    timeout = 900                               # 15min
    on-timeout = loginctl lock-session
}

# Suspend system
listener {
    timeout = 1800                              # 30min
    on-timeout = systemctl suspend
}
