################
### KEYBINDS ###
################

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $Mod1, RETURN, exec, $terminal # open terminal
bind = $Mod1, SPACE, exec, $launcher # app launcher
bind = $Mod1, F, exec, $FM_TUI # file manager
bind = $Mod1 $Mod2, F, exec, $FM_GUI # TUI file manager
bind = $Mod1, Z, exec, $browser # browser
bind = $Mod1 $Mod2, Z, exec, $browser --private-window # private browser
#bind = $Mod1, Z, exec, $secondBrowser # second browser
bind = $Mod1, S, exec, $chat # chat
bind = $Mod1, D, exec, $discord # discord
bind = $Mod1, Q, killactive, # close window
bind = $Mod1, R, exec, hyprctl reload # reload hyprland
bind = $Mod1, L, exec, $ipc lockScreen lock # lock the screen
bind = $Mod1 $Mod2, L, exec, systemctl suspend # sleep
bind = $Mod1, M, exit, # EXITS HYPRLAND
bind = $Mod1 $Mod2, M, exec, systemctl poweroff # shutdown
bind = $Mod1, V, togglefloating, # toggle floating windows
bind = $Mod1, P, pseudo, # dwindle
# bind = $Mod1, J, togglesplit, # dwindle
# bind = $Mod1 $Mod2, R, exec, pkill waybar && hyprctl dispatch exec waybar # reload waybar
bind = $Mod1, comma, exec, $ipc settings toggle
bind = CTRL SHIFT, ESCAPE, exec, $taskManager # task manager
bind = CTRL ALT, DELETE, exec, $sessionMenu # logout menu

# Move focus with mainMod + arrow keys
bind = $Mod1, left, movefocus, l
bind = $Mod1, mouse_left, movefocus, l
bind = $Mod1, right, movefocus, r
bind = $Mod1, mouse_right, movefocus, r
bind = $Mod1, up, movefocus, u
bind = $Mod1, down, movefocus, d

# Move windows around
bind = $Mod1 $Mod2, Left, movewindow, l
bind = $Mod1 $Mod2, Right, movewindow, r
bind = $Mod1 $Mod2, Up, movewindow, u
bind = $Mod1 $Mod2, Down, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $Mod1, 1, workspace, 1
bind = $Mod1, 2, workspace, 2
bind = $Mod1, 3, workspace, 3
bind = $Mod1, 4, workspace, 4
bind = $Mod1, 5, workspace, 5
bind = $Mod1, 6, workspace, 6
bind = $Mod1, 7, workspace, 7
bind = $Mod1, 8, workspace, 8
bind = $Mod1, 9, workspace, 9
bind = $Mod1, 0, workspace, 10

# Move active window to a workspace with mainMod + $Mod2 + [0-9]
bind = $Mod1 $Mod2, 1, movetoworkspace, 1
bind = $Mod1 $Mod2, 2, movetoworkspace, 2
bind = $Mod1 $Mod2, 3, movetoworkspace, 3
bind = $Mod1 $Mod2, 4, movetoworkspace, 4
bind = $Mod1 $Mod2, 5, movetoworkspace, 5
bind = $Mod1 $Mod2, 6, movetoworkspace, 6
bind = $Mod1 $Mod2, 7, movetoworkspace, 7
bind = $Mod1 $Mod2, 8, movetoworkspace, 8
bind = $Mod1 $Mod2, 9, movetoworkspace, 9
bind = $Mod1 $Mod2, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
# bind = $Mod1, S, togglespecialworkspace, magic
# bind = $Mod1 $Mod2, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $Mod1, mouse_down, workspace, e-1
bind = $Mod1, mouse_up, workspace, e+1

# Screenshot a window
bind = $Mod1 SHIFT, S, exec, hyprshot -m window
# Screenshot a monitor
bind = $Mod1 ALT, S, exec, hyprshot -m output
# Screenshot a region
bind = $Mod1 CTRL, S, exec, hyprshot -m region

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $Mod1, mouse:272, movewindow
bindm = $Mod1, mouse:273, resizewindow

# Volume controls
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = $Mod1, equal, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = $Mod1, minus, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Mute toggle
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = $Mod1 $Mod2, equal, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = $Mod1 $Mod2, minus, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
