# See https://wiki.hypr.land/Configuring/Keywords/
$Mod1 = SUPER # Sets "Windows" key as main modifier
$Mod2 = SHIFT # Sets "Shift" as second modifier

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Noctalia IPC
$ipc = qs -c noctalia-shell ipc call

# Set programs that you use
$terminal = ghostty
$browser = zen-browser
$chat = signal-desktop --password-store=gnome-libsecret
$discord = vesktop
$sessionMenu = $ipc sessionMenu toggle
$FM_GUI = thunar
$FM_TUI = $terminal -e yazi
#$menu = rofi -show drun
$taskManager = $terminal -e btop
$launcher = $ipc launcher toggle

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Adwaita

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
# gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = keychron--keychron-link-
    sensitivity = -0.5
}
